site_name: Mastering Python
docs_dir: "doc"

nav:
  - Home: index.md
  - Basics:
      - Python Paradigms: basics/python_paradigm.md
      - Variables and Datatypes: basics/variables_and_datatypes.md
      - Operators: basics/operators.md
      - Control Flow: basics/control_flow.md
      - Exception Handling: basics/exception.md
      - Modules and Packages: basics/modules_packages.md
      - Object References, Mutability, and Recycling: basics/object_handling.md
      - Hashable Objects: basics/hashable.md
  - Objects:
      - Classes: classes_objects/basic_classes.md
      - Data Model: classes_objects/data_model.md
      - Interfaces, Protocols, and ABCs: classes_objects/interfaces_protocols_abc.md
      - Inheritance: classes_objects/inheritance.md
  - Functions:
      - Basic: functions/basic.md
      - Parameters: functions/parameters.md
      - Variables Scope: functions/variables_scope.md
      - High-Order and Lambda Function: functions/hof_lamda_functions.md
      - User-Defined Callable Types: functions/user_defined_callable_types.md
      - Type Hits: functions/type_hits.md
  - Data Structures:
    - Built-In Sequences: data_structures/sequence.md
    - List: data_structures/list.md
    - Tuple: data_structures/tuple.md
    - Set: data_structures/set.md
    - Dict: data_structures/dict.md
  - Closures and Decorators:
    - Closures: decorators_closures/closures.md
    - Decorators: decorators_closures/decorators.md
  - Design Patterns: 
    - Gang of Four - Design Patterns: design_patterns/index.md
    - Iterators: design_patterns/iterators.md
  - Built-In Examples:
    - Functools Module: builtin_modules_examples/functools_module.md
    - Operator Module: builtin_modules_examples/operator_module.md

theme:
  name: material
  language: en
  logo: images/python.png
  favicon: images/py.svg
  palette:
      scheme: slate
      primary: blue
      accent: yellow
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - markdown-exec
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: src
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
